modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "logo.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.appliedcooking]]
modId = "ae2"
mandatory = true
versionRange = "[15.0.4-beta,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.appliedcooking]]
modId = "cookingforblockheads"
mandatory = true
versionRange = "[16.0.0,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.appliedcooking]]
modId = "sebastrnlib"
mandatory = true
versionRange = "[4.0.0,)"
ordering = "AFTER"
side = "BOTH"
